### ISSUE TITLE
alternative way to do NSEW

### ISSUE THREAD

**Issue by jedwards1211** [jedwards1211/metacave#11]
Apparently in walls if you want to do NSEW, you just create two LRUDs for a station with facing angles for north and east:

```
A *2,3,-,-,0* ; east/west
A *4,5,-,-,90d* ; north/south
```

The same thing is already possible in our format, so we could just nix the `nsew` field to simplify it.
@vpicaver what do you think?

**Comment by vpicaver** [comment]
Hmmm, that's interesting. It's almost like a splay shot without zero
inclination. Anyways how can we currently describe that in metacave? I
don't think you can have two of the same keys ("lrud") JSON object.

**Comment by vpicaver** [comment]
with a zero inclination*

**Comment by jedwards1211** [comment]
yeah, you can't have two keys, I mean by having two station entries with the same station name and different LRUDs.

**Comment by vpicaver** [comment]
I think add having repeated station objects for just lrud would adds more
complexity than its worth to support. If you saw the format for the first
time like this, would you find it confusing? I think I would.

On the other side, it would be nice to support multiple lrud measurements.
I know a bunch of people do two measurements if there's a floor step or
ceiling step. Could we make the lrud property store an object with "left",
"right" "up" "down" properties. Each lrud property could store and array of
measurements, including the azm for left or right measurement. Either
way, I'm not sure how this would work in the editor.

At the end of that day lrud and nsew are pretty much splay shots. It would
be cool to make a passage generator off of splay points. Almost like a
sparse cloud. Although that a bit off topic from this bug.

Philip

On Tuesday, January 26, 2016, Andy Edwards notifications@github.com wrote:

> yeah, you can't have two keys, I mean by having two station entries with
> the same station name and different LRUDs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/issues/11#issuecomment-175306837
> .

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
Yeah, the extra complexity is undeniable :)  I guess from a 3D modeling point of view it's the same problem as trying to include splay shots in the 3D mesh generation

**Comment by jedwards1211** [comment]
(that is to say, LRUDs and splay shots are sort of the same thing, except with LRUDs you need extra logic do determine which way they're facing)
