### ISSUE TITLE
simpler unit overrides

### ISSUE THREAD

**Issue by jedwards1211** [jedwards1211/metacave#12]
Now that we're using strings for all numbers, I think we should just put unit overrides in those strings instead of using arrays.  So instead of doing

```
    dist: ["4", "ft", "3", "in"]
```

We would just do

```
    dist: "4 ft 3 in"
```

I'd say we just require space between the numbers and units, so that parsing it is as simple as splitting on `/\s+/` and using the existing logic for processing units.

@vpicaver dost thou concur?

**Comment by vpicaver** [comment]
Sounds good to me

On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
wrote:

> Now that we're using strings for all numbers, I think we should just put
> unit overrides in those strings instead of using arrays. So instead of doing
> 
> ```
> dist: ["4", "ft", "3", "in"]
> ```
> 
> We would just do
> 
> ```
> dist: "4 ft 3 in"
> ```
> 
> I'd say we just require space between the numbers and units, so that
> parsing it is as simple as splitting on /\s+/ and using the existing
> logic for processing units.
> 
> @vpicaver https://github.com/vpicaver dost thou concur?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/issues/12.

## 

Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
yay!

**Comment by jedwards1211** [comment]
done

**Comment by vpicaver** [comment]
Cool :)

On Wednesday, January 27, 2016, Andy Edwards notifications@github.com
wrote:

> Closed #12 https://github.com/jedwards1211/metacave/issues/12.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jedwards1211/metacave/issues/12#event-528624677.

## 

Phi|ip

Sent from Gmail Mobile
